controller_list:
  - name: fake_planner_1_controller
    type: $(arg execution_type)
    joints:
      - revolute_joint_1
      - revolute_joint_2
  - name: fake_planner_2_controller
    type: $(arg execution_type)
    joints:
      - joint_3
  - name: fake_planner_3_controller
    type: $(arg execution_type)
    joints:
      - joint_4
initial:  # Define initial robot poses.
  - group: planner_1
    pose: home
  - group: planner_2
    pose: up
  - group: planner_3
    pose: default_push